version: '3.4'

services:
  mymoneyassistant:
    image: ${DOCKER_REGISTRY-}mymoneyassistant
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    build:
      context: .
      dockerfile: MyMoneyAssistant/Dockerfile
    depends_on:
        "postgres":
            condition: service_started
    ports:
        - "8080:8080"
  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
        POSTGRES_PASSWORD: postgres
    ports:
        - "8001:5432" 